-- Skynet_AI
-- Author: Safeguard
-- DateCreated: 1/31/2023 4:24:10 PM
--------------------------------------------------------------
--AI LIST TYPES
INSERT OR IGNORE INTO AiListTypes			
		(ListType)
VALUES
		('SGA_SKYNET_DISTRICTS'),
		('SGA_SKYNET_TECH'),
		('SGA_SKYNET_CIVICS'),
		('SGA_SKYNET_IMPROVEMENTS'),
		('SGA_SKYNET_PROJECTS'),
		('SGA_SKYNET_UNITS'),
		('SGA_SKYNET_DIPLO'),
		('SGA_SKYNET_BUILDINGS'),
		('SGA_SKYNET_YIELDS'),
		('SGA_SKYNET_AI_OPERATIONS'),
		('SGA_SKYNET_ARMY'),
		('SGA_SKYNET_COUNTER_STRATEGIES'); -- GLOBAL HACK PROJECT FAVORS

--AI LISTS
INSERT OR IGNORE INTO AiLists	
		(ListType, LeaderType, System)
VALUES		
		('SGA_SKYNET_DISTRICTS', 'TRAIT_SGA_LEADER_SKYNET_SUPERINTELLIGENCE', 'Districts'),
		('SGA_SKYNET_IMPROVEMENTS',	'TRAIT_SGA_LEADER_SKYNET_SUPERINTELLIGENCE', 'Improvements'),
		('SGA_SKYNET_TECH',	'TRAIT_SGA_LEADER_SKYNET_SUPERINTELLIGENCE', 'Technologies'),
		('SGA_SKYNET_CIVICS', 'TRAIT_SGA_LEADER_SKYNET_SUPERINTELLIGENCE', 'Civics'),
		('SGA_SKYNET_DIPLO', 'TRAIT_SGA_LEADER_SKYNET_SUPERINTELLIGENCE', 'DiplomaticActions'),
		('SGA_SKYNET_PROJECTS',	'TRAIT_SGA_LEADER_SKYNET_SUPERINTELLIGENCE', 'Projects'),
		('SGA_SKYNET_UNITS', 'TRAIT_SGA_LEADER_SKYNET_SUPERINTELLIGENCE', 'Units'),
		('SGA_SKYNET_BUILDINGS', 'TRAIT_SGA_LEADER_SKYNET_SUPERINTELLIGENCE', 'Buildings'),
		('SGA_SKYNET_YIELDS', 'TRAIT_SGA_LEADER_SKYNET_SUPERINTELLIGENCE', 'Yields'),
		('SGA_SKYNET_AI_OPERATIONS', 'TRAIT_SGA_LEADER_SKYNET_SUPERINTELLIGENCE', 'AiOperationTypes'),
		('SGA_SKYNET_ARMY',	'TRAIT_SGA_LEADER_SKYNET_SUPERINTELLIGENCE', 'PseudoYields'),
		('SGA_SKYNET_COUNTER_STRATEGIES', 'TRAIT_LEADER_MAJOR_CIV', 'Projects'); -- GLOBAL HACK PROJECT FAVORS

--AI FAVORED ITEMS
INSERT OR IGNORE INTO AiFavoredItems	
	(ListType,							Item,												Favored, Value)
VALUES
		--- CENTRAL BUILDINGS
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_CENTRAL_CORE',						1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_HUB',									1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_ORBITAL_PLATFORM',					1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_GRIFFITH_OBSERVATORY',				1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_CYBERDYNE_SYSTEMS_HEADQUARTERS',		1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_CONTROL_NEXUS',						1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_TIME_DISPLACEMENT_EQUIPMENT',			1,		100),
		-- RESEARCH FACILITIES BUILDINGS
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_VLA',									1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_RD_FACILITY',							1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_BAKERS_HOLLOW',						1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_BEDFORD_FALLS',						1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_CYBERDYNE_SYSTEMS_FACILITY',			1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_CYBER_RESEARCH_SYSTEMS_FACILITY',		1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_CYBERDYNE_SYSTEMS_LABORATORY',		1,		100),
		-- DEVELOPMENT FACILITIES BUILDINGS
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_COLD_FUSION_REACTOR',					1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_SECRET_TERMINATOR_LAB',				1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_TIER_1_TERMINATOR_FACTORY',			1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_TIER_1_HK_GROUND_FACTORY',			1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_TIER_1_HK_AERIAL_FACTORY',			1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_PLASMA_GENERATOR',					1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_TIER_2_TERMINATOR_FACTORY',			1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_TIER_2_HK_GROUND_FACTORY',			1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_TIER_2_HK_AERIAL_FACTORY',			1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_COLD_FUSION_GENERATOR',				1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_TIER_3_TERMINATOR_FACTORY',			1,		100),
		('SGA_SKYNET_BUILDINGS','BUILDING_SGA_SKYNET_ANTIMATTER_GENERATOR',					1,		100),
		-- ENCAMPMENT FACILITIES BUILDINGS/OTHER
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_WORK_CAMP',							1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_DEPOT_37',							1,		100),
		('SGA_SKYNET_BUILDINGS', 'BUILDING_SGA_SKYNET_HK_AERIAL_HANGAR',					1,		100),
		-- DISTRICTS
		('SGA_SKYNET_DISTRICTS', 'DISTRICT_SGA_SKYNET_DEVELOPMENT_FACILITIES',				1,		100),
		('SGA_SKYNET_DISTRICTS', 'DISTRICT_SGA_SKYNET_RESEARCH_FACILITIES',					1,		100),
		('SGA_SKYNET_DISTRICTS', 'DISTRICT_SGA_SKYNET_CENTRAL',								1,		100),
		('SGA_SKYNET_DISTRICTS', 'DISTRICT_AQUEDUCT',										0,		NULL),
		-- IMPROVEMENT
		('SGA_SKYNET_IMPROVEMENTS',	'IMPROVEMENT_SGA_SKYNET_OUTPOST',						1,		100),
		('SGA_SKYNET_IMPROVEMENTS',	'IMPROVEMENT_FARM',										0,		NULL),
		('SGA_SKYNET_IMPROVEMENTS',	'IMPROVEMENT_MINE',										1,		100),
		-- TECH
		('SGA_SKYNET_TECH', 'TECH_MILITARY_TACTICS',										1,		100),
		('SGA_SKYNET_TECH',	'TECH_MILITARY_SCIENCE',										1,		100),
		('SGA_SKYNET_TECH',	'TECH_COMBINED_ARMS',											1,		100),
		('SGA_SKYNET_TECH',	'TECH_ENGINEERING',												1,		100),		
		('SGA_SKYNET_TECH',	'TECH_WRITING',													1,		100),
		('SGA_SKYNET_TECH',	'TECH_APPRENTICESHIP',											1,		100),
		('SGA_SKYNET_TECH',	'TECH_LASERS',													1,		100),
		('SGA_SKYNET_TECH',	'TECH_INDUSTRIALIZATION',										1,		100),
		-- CIVICS
		('SGA_SKYNET_CIVICS', 'CIVIC_DEFENSIVE_TACTICS',									1,		100),
		('SGA_SKYNET_CIVICS', 'CIVIC_MERCENARIES',											1,		100),
		('SGA_SKYNET_CIVICS', 'CIVIC_SCORCHED_EARTH',										1,		100),
		('SGA_SKYNET_CIVICS', 'CIVIC_MOBILIZATION',											1,		100),
		('SGA_SKYNET_CIVICS', 'CIVIC_THE_ENLIGHTENMENT',									1,		100),
		('SGA_SKYNET_CIVICS', 'CIVIC_URBANISATION',											1,		100),
		('SGA_SKYNET_CIVICS', 'CIVIC_TOTALITARIANISM',										1,		100),
		('SGA_SKYNET_CIVICS', 'CIVIC_NUCLEAR_PROGRAM',										1,		100),
		-- UNITS
		('SGA_SKYNET_UNITS', 'UNIT_SGA_SKYNET_T600',										1,		100),
		('SGA_SKYNET_UNITS', 'UNIT_SGA_SKYNET_T825',										1,		100),
		('SGA_SKYNET_UNITS', 'UNIT_SGA_SKYNET_T800',										1,		150),
		('SGA_SKYNET_UNITS', 'UNIT_SGA_SKYNET_HK_SPIDER_TANK',								1,		100),
		('SGA_SKYNET_UNITS', 'UNIT_SGA_SKYNET_HK_AERIAL',									1,		100),
		('SGA_SKYNET_UNITS', 'UNIT_SPY',													1,		100),
		('SGA_SKYNET_UNITS', 'UNIT_SPEC_OPS',												0,		NULL),-- NO SPEC OPS GOT DAMN!!!
		('SGA_SKYNET_UNITS', 'UNIT_SGA_SKYNET_HK_BOMBER',									1,		100),
		('SGA_SKYNET_UNITS', 'UNIT_SGA_SKYNET_HK_FIGHTER',									1,		100),
		('SGA_SKYNET_UNITS', 'UNIT_SGA_SKYNET_T900',										1,		100),
		('SGA_SKYNET_UNITS', 'UNIT_SGA_SKYNET_T810',										1,		100),
		('SGA_SKYNET_UNITS', 'UNIT_SGA_SKYNET_HK_TANK',										1,		100),
		-- DIPLO ACTION
		('SGA_SKYNET_DIPLO', 'DIPLOACTION_DECLARE_TERRITORIAL_WAR',							1,		100),
		('SGA_SKYNET_DIPLO', 'DIPLOACTION_MAKE_PEACE',										0,		NULL),
		('SGA_SKYNET_DIPLO', 'DIPLOACTION_PROPOSE_PEACE_DEAL',								0,		NULL),
		('SGA_SKYNET_DIPLO', 'DIPLOACTION_JOINT_WAR',										1,		100),
		-- YIELDS 
		('SGA_SKYNET_YIELDS', 'YIELD_CULTURE',												0,		NULL),
		('SGA_SKYNET_YIELDS', 'YIELD_FOOD',													0,		NULL),
		('SGA_SKYNET_YIELDS', 'YIELD_FAITH',												0,		NULL),
		-- ARMY
		('SGA_SKYNET_ARMY',	'PSEUDOYIELD_STANDING_ARMY_NUMBER',								1,		250),
		('SGA_SKYNET_ARMY',	'PSEUDOYIELD_STANDING_ARMY_VALUE',								1,		250),
		('SGA_SKYNET_ARMY',	'PSEUDOYIELD_NUCLEAR_WEAPON',									1,		100),
		-- OTHERS
		('SGA_SKYNET_AI_OPERATIONS', 'CITY_ASSAULT',										1,		NULL),
		('SGA_SKYNET_COUNTER_STRATEGIES', 'PROJECT_SGA_SKYNET_GLOBAL_HACK_T800',			1,		NULL), -- GLOBAL HACK PROJECT FAVORS
		('SGA_SKYNET_COUNTER_STRATEGIES', 'PROJECT_SGA_SKYNET_GLOBAL_HACK_HK_TANK',			1,		NULL), -- GLOBAL HACK PROJECT FAVORS
		('SGA_SKYNET_COUNTER_STRATEGIES', 'PROJECT_SGA_SKYNET_GLOBAL_HACK_HK_AERIAL',		1,		NULL); -- GLOBAL HACK PROJECT FAVORS

