-- Skynet_Colors
-- Author: Safeguard
-- DateCreated: 1/17/2023 4:40:03 PM
--------------------------------------------------------------

--LEADER COLORS
--PLAYERCOLORS
INSERT INTO Colors(Type, Color)
VALUES	('COLOR_PLAYER_SGA_SKYNET_LEADER_SKYNET_PRIMARY', '0,0,102,255'), -- 1 DARK BLUE
		('COLOR_PLAYER_SGA_SKYNET_LEADER_SKYNET_SECONDARY', '255,255,255,255'), -- 1 WHITE
		('COLOR_PLAYER_SGA_SKYNET_LEADER_SKYNET_PRIMARY1', '51,51,153,255'), -- 2 BLUEY GRAY
		('COLOR_PLAYER_SGA_SKYNET_LEADER_SKYNET_SECONDARY1', '255,255,255,255'), -- 2 WHITE
		('COLOR_PLAYER_SGA_SKYNET_LEADER_SKYNET_PRIMARY2', '102,0,102,255'), -- 3 PURPLE
		('COLOR_PLAYER_SGA_SKYNET_LEADER_SKYNET_SECONDARY2', '255,255,255,255'); -- 3 WHITE

INSERT INTO PlayerColors (Type, Usage, 
									PrimaryColor,	
									SecondaryColor,	
									Alt1PrimaryColor, 
									Alt1SecondaryColor,
									Alt2PrimaryColor,
									Alt2SecondaryColor)
VALUES	('LEADER_SGA_LEADER_SKYNET', 'Unique', 
		'COLOR_PLAYER_SGA_SKYNET_LEADER_SKYNET_PRIMARY', -- 1
		'COLOR_PLAYER_SGA_SKYNET_LEADER_SKYNET_SECONDARY', -- 1
		'COLOR_PLAYER_SGA_SKYNET_LEADER_SKYNET_PRIMARY1', -- 2
		'COLOR_PLAYER_SGA_SKYNET_LEADER_SKYNET_SECONDARY1', -- 2
		'COLOR_PLAYER_SGA_SKYNET_LEADER_SKYNET_PRIMARY2', -- 3
		'COLOR_PLAYER_SGA_SKYNET_LEADER_SKYNET_SECONDARY2'); -- 3


