--CONFIG DATA
--VANILLA PLAYERS
INSERT INTO Players	
		(CivilizationType,				Portrait,								PortraitBackground,						LeaderType,						LeaderName,							LeaderIcon,								LeaderAbilityName,												LeaderAbilityDescription,												LeaderAbilityIcon,									CivilizationName,						CivilizationIcon,					CivilizationAbilityName,								CivilizationAbilityDescription,									CivilizationAbilityIcon)
VALUES	('CIVILIZATION_SGA_SKYNET',		'LEADER_LEADER_SKYNET_NEUTRAL.dds',		'LEADER_JOHN_CURTIN_BACKGROUND',		'LEADER_SGA_LEADER_SKYNET',		'LOC_LEADER_SGA_LEADER_SKYNET',		'ICON_LEADER_SGA_LEADER_SKYNET',		'LOC_TRAIT_SGA_LEADER_SKYNET_SUPERINTELLIGENCE_NAME',	'LOC_TRAIT_SGA_LEADER_SKYNET_SUPERINTELLIGENCE_DESCRIPTION',		'ICON_LEADER_SGA_LEADER_SKYNET',		'LOC_CIVILIZATION_SGA_SKYNET_NAME',		'ICON_CIVILIZATION_SGA_SKYNET',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_RISE_OF_THE_MACHINES_NAME',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_RISE_OF_THE_MACHINES_DESCRIPTION',		'ICON_CIVILIZATION_SGA_SKYNET');
		
INSERT INTO PlayerItems	
		(CivilizationType,				LeaderType,						Type,													Icon,														Name,									  						Description,															SortIndex)
VALUES	('CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'TRAIT_CIVILIZATION_SGA_SKYNET_HUNTER_KILLERS',			'ICON_TRAIT_CIVILIZATION_SGA_SKYNET_HUNTER_KILLERS',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_HUNTER_KILLERS_NAME',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_HUNTER_KILLERS_DESCRIPTION',			1),
		('CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'TRAIT_CIVILIZATION_SGA_SKYNET_BUILDING_FACILITIES',		'ICON_TRAIT_CIVILIZATION_SGA_SKYNET_BUILDING_FACILITIES',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_BUILDING_FACILITIES_NAME',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_BUILDING_FACILITIES_DESCRIPTION',		2),
		('CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'DISTRICT_SGA_SKYNET_CENTRAL',							'ICON_DISTRICT_SGA_SKYNET_CENTRAL',							'LOC_DISTRICT_SGA_SKYNET_CENTRAL_NAME',							'LOC_DISTRICT_SGA_SKYNET_CENTRAL_DESCRIPTION',							3),
		('CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'DISTRICT_SGA_SKYNET_RESEARCH_FACILITIES',				'ICON_DISTRICT_SGA_SKYNET_RESEARCH_FACILITIES',				'LOC_DISTRICT_SGA_SKYNET_RESEARCH_FACILITIES_NAME',				'LOC_DISTRICT_SGA_SKYNET_RESEARCH_FACILITIES_DESCRIPTION',				4),
		('CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'DISTRICT_SGA_SKYNET_DEVELOPMENT_FACILITIES',			'ICON_DISTRICT_SGA_SKYNET_DEVELOPMENT_FACILITIES',			'LOC_DISTRICT_SGA_SKYNET_DEVELOPMENT_FACILITIES_NAME',			'LOC_DISTRICT_SGA_SKYNET_DEVELOPMENT_FACILITIES_DESCRIPTION',			5),
		('CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'DISTRICT_SGA_SKYNET_ENCAMPMENT_FACILITIES',			'ICON_DISTRICT_SGA_SKYNET_ENCAMPMENT_FACILITIES',			'LOC_DISTRICT_SGA_SKYNET_ENCAMPMENT_FACILITIES_NAME',			'LOC_DISTRICT_SGA_SKYNET_ENCAMPMENT_FACILITIES_DESCRIPTION',			6);
			
--RISE AND FALL
INSERT INTO Players 
			(Domain,					CivilizationType,					Portrait,							PortraitBackground,							LeaderType,						LeaderName,									LeaderIcon,								LeaderAbilityName,								LeaderAbilityDescription,												LeaderAbilityIcon,						CivilizationName,							CivilizationIcon,						CivilizationAbilityName,						CivilizationAbilityDescription,								CivilizationAbilityIcon)
VALUES ('Players:Expansion1_Players',  'CIVILIZATION_SGA_SKYNET',		'LEADER_LEADER_SKYNET_NEUTRAL.dds',		'LEADER_JOHN_CURTIN_BACKGROUND',		'LEADER_SGA_LEADER_SKYNET',		'LOC_LEADER_SGA_LEADER_SKYNET',		'ICON_LEADER_SGA_LEADER_SKYNET',		'LOC_TRAIT_SGA_LEADER_SKYNET_SUPERINTELLIGENCE_NAME',	'LOC_TRAIT_SGA_LEADER_SKYNET_SUPERINTELLIGENCE_DESCRIPTION',		'ICON_LEADER_SGA_LEADER_SKYNET',		'LOC_CIVILIZATION_SGA_SKYNET_NAME',		'ICON_CIVILIZATION_SGA_SKYNET',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_RISE_OF_THE_MACHINES_NAME',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_RISE_OF_THE_MACHINES_DESCRIPTION',				'ICON_CIVILIZATION_SGA_SKYNET');

INSERT INTO PlayerItems	
		(Domain,							CivilizationType,				LeaderType,						Type,													Icon,														Name,									  					Description,											SortIndex)
VALUES	('Players:Expansion1_Players',		'CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'TRAIT_CIVILIZATION_SGA_SKYNET_HUNTER_KILLERS',			'ICON_TRAIT_CIVILIZATION_SGA_SKYNET_HUNTER_KILLERS',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_HUNTER_KILLERS_NAME',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_HUNTER_KILLERS_DESCRIPTION',			1),
		('Players:Expansion1_Players',		'CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'TRAIT_CIVILIZATION_SGA_SKYNET_BUILDING_FACILITIES',		'ICON_TRAIT_CIVILIZATION_SGA_SKYNET_BUILDING_FACILITIES',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_BUILDING_FACILITIES_NAME',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_BUILDING_FACILITIES_DESCRIPTION',		2),
		('Players:Expansion1_Players',		'CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'DISTRICT_SGA_SKYNET_CENTRAL',							'ICON_DISTRICT_SGA_SKYNET_CENTRAL',							'LOC_DISTRICT_SGA_SKYNET_CENTRAL_NAME',							'LOC_DISTRICT_SGA_SKYNET_CENTRAL_DESCRIPTION',							3),
		('Players:Expansion1_Players',		'CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'DISTRICT_SGA_SKYNET_RESEARCH_FACILITIES',				'ICON_DISTRICT_SGA_SKYNET_RESEARCH_FACILITIES',				'LOC_DISTRICT_SGA_SKYNET_RESEARCH_FACILITIES_NAME',				'LOC_DISTRICT_SGA_SKYNET_RESEARCH_FACILITIES_DESCRIPTION',				4),
		('Players:Expansion1_Players',		'CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'DISTRICT_SGA_SKYNET_DEVELOPMENT_FACILITIES',			'ICON_DISTRICT_SGA_SKYNET_DEVELOPMENT_FACILITIES',			'LOC_DISTRICT_SGA_SKYNET_DEVELOPMENT_FACILITIES_NAME',			'LOC_DISTRICT_SGA_SKYNET_DEVELOPMENT_FACILITIES_DESCRIPTION',			5),
		('Players:Expansion1_Players',		'CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'DISTRICT_SGA_SKYNET_ENCAMPMENT_FACILITIES',			'ICON_DISTRICT_SGA_SKYNET_ENCAMPMENT_FACILITIES',			'LOC_DISTRICT_SGA_SKYNET_ENCAMPMENT_FACILITIES_NAME',			'LOC_DISTRICT_SGA_SKYNET_ENCAMPMENT_FACILITIES_DESCRIPTION',			6);

--GATHERING STORM
INSERT INTO Players 
		(Domain,							CivilizationType,						Portrait,						PortraitBackground,							LeaderType,						LeaderName,									LeaderIcon,								LeaderAbilityName,								LeaderAbilityDescription,												LeaderAbilityIcon,						CivilizationName,							CivilizationIcon,						CivilizationAbilityName,						CivilizationAbilityDescription,								CivilizationAbilityIcon)
VALUES ('Players:Expansion2_Players',  'CIVILIZATION_SGA_SKYNET',		'LEADER_LEADER_SKYNET_NEUTRAL.dds',		'LEADER_JOHN_CURTIN_BACKGROUND',		'LEADER_SGA_LEADER_SKYNET',		'LOC_LEADER_SGA_LEADER_SKYNET',		'ICON_LEADER_SGA_LEADER_SKYNET',		'LOC_TRAIT_SGA_LEADER_SKYNET_SUPERINTELLIGENCE_NAME',	'LOC_TRAIT_SGA_LEADER_SKYNET_SUPERINTELLIGENCE_DESCRIPTION',		'ICON_LEADER_SGA_LEADER_SKYNET',		'LOC_CIVILIZATION_SGA_SKYNET_NAME',		'ICON_CIVILIZATION_SGA_SKYNET',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_RISE_OF_THE_MACHINES_NAME',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_RISE_OF_THE_MACHINES_DESCRIPTION',				'ICON_CIVILIZATION_SGA_SKYNET');

INSERT INTO PlayerItems	
		(Domain,							CivilizationType,				LeaderType,						Type,													Icon,														Name,									  					Description,											SortIndex)
VALUES	('Players:Expansion2_Players',		'CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'TRAIT_CIVILIZATION_SGA_SKYNET_HUNTER_KILLERS',			'ICON_TRAIT_CIVILIZATION_SGA_SKYNET_HUNTER_KILLERS',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_HUNTER_KILLERS_NAME',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_HUNTER_KILLERS_DESCRIPTION',			1),
		('Players:Expansion2_Players',		'CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'TRAIT_CIVILIZATION_SGA_SKYNET_BUILDING_FACILITIES',		'ICON_TRAIT_CIVILIZATION_SGA_SKYNET_BUILDING_FACILITIES',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_BUILDING_FACILITIES_NAME',		'LOC_TRAIT_CIVILIZATION_SGA_SKYNET_BUILDING_FACILITIES_DESCRIPTION',		2),
		('Players:Expansion2_Players',		'CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'DISTRICT_SGA_SKYNET_CENTRAL',							'ICON_DISTRICT_SGA_SKYNET_CENTRAL',							'LOC_DISTRICT_SGA_SKYNET_CENTRAL_NAME',							'LOC_DISTRICT_SGA_SKYNET_CENTRAL_DESCRIPTION',							3),
		('Players:Expansion2_Players',		'CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'DISTRICT_SGA_SKYNET_RESEARCH_FACILITIES',				'ICON_DISTRICT_SGA_SKYNET_RESEARCH_FACILITIES',				'LOC_DISTRICT_SGA_SKYNET_RESEARCH_FACILITIES_NAME',				'LOC_DISTRICT_SGA_SKYNET_RESEARCH_FACILITIES_DESCRIPTION',				4),
		('Players:Expansion2_Players',		'CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'DISTRICT_SGA_SKYNET_DEVELOPMENT_FACILITIES',			'ICON_DISTRICT_SGA_SKYNET_DEVELOPMENT_FACILITIES',			'LOC_DISTRICT_SGA_SKYNET_DEVELOPMENT_FACILITIES_NAME',			'LOC_DISTRICT_SGA_SKYNET_DEVELOPMENT_FACILITIES_DESCRIPTION',			5),
		('Players:Expansion2_Players',		'CIVILIZATION_SGA_SKYNET',		'LEADER_SGA_LEADER_SKYNET',		'DISTRICT_SGA_SKYNET_ENCAMPMENT_FACILITIES',			'ICON_DISTRICT_SGA_SKYNET_ENCAMPMENT_FACILITIES',			'LOC_DISTRICT_SGA_SKYNET_ENCAMPMENT_FACILITIES_NAME',			'LOC_DISTRICT_SGA_SKYNET_ENCAMPMENT_FACILITIES_DESCRIPTION',			6);

--MAPSUPPORTEDVALUES
--INSERT INTO MapSupportedValues	
--		(Value,						Domain, Map)
--SELECT	'LEADER_SGA_LEADER_SKYNET',		Domain, Map
--FROM MapSupportedValues WHERE Value= '';